[package]
name = "alcoholic_jwt"
version = "0.1.0"
authors = ["Vincent Ambo <vincent@aprila.no>"]

[dependencies]
base64 = "0.9"
openssl = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
